
debug:
	webpack --config webpack.config.js --progress --color
release:
	NODE_ENV=production webpack --config webpack.config.js --progress --color
watch:debug
	webpack --config webpack.config.js --progress --color --watch
